name: Build and deploy Jekyll site to GitHub Pages

# Triggered by external to REST API
on:
  - workflow_dispatch
  - push

# Cancel any workflows that are already running. This ensures
# that the latest-triggered of any competing workflow runs is 
# the one that will finish.
concurrency:
  group: win-eap-pages
  cancel-in-progress: true

# Give auth step permission to save an OAuth 2.0 access token for 
# use in fetch step
permissions:
  id-token: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Not needed with a .ruby-version file
      - run: |
          ln -s /usr/local/bin/ruby /usr/bin/ruby-2.7 # from https://stackoverflow.com/questions/36837382/usr-bin-env-ruby-no-such-file-or-directory-cannot-use-bundler-nor-rails
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.GOOGLE_WIP }}'
          service_account: '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}'
          access_token_scopes: 'https://www.googleapis.com/auth/spreadsheets.readonly'
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: "https://sheets.googleapis.com/v4/spreadsheets/${{ secrets.GSHEET_ID }}/values:batchGet?ranges=A1%3AW1000&majorDimension=COLUMNS"
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ steps.auth.outputs.access_token }}"} }'
          save-location: _data
          save-name: raw_resources
          set-output: false # do not set environment variable
      - name: Process spreadsheet data with jq
        run: |
          pip install csvkit # get csvjson
          ls -l _data
          head _data/raw_resources.json
          jq -r ".valueRanges[0].values | .[] | @csv" < _data/raw_resources.json > _data/temp.csv
          echo "Rows: `wc -l _data/temp.csv`"
          csvjson _data/temp.csv > _data/resources.json
          rm _data/temp.csv _data/raw_resources.json
          head -2 _data/resources.json

      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

#          bundle exec jekyll build
#          rm -r _data 
#          rsync -a --delete _site/* ./
#          touch .nojekyll
#          git add .
#          git commit -m "Rendered site"
#          git push --force
